Imported from bookcase-0.8.1.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -458,7 +458,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CONF_FILES CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE WOVERLOADED_VIRTUAL USE_EXCEPTIONS USE_RTTI CXXCPP NOOPT_CXXFLAGS NOOPT_CFLAGS KDE_USE_FINAL_TRUE KDE_USE_FINAL_FALSE KDE_USE_CLOSURE_TRUE KDE_USE_CLOSURE_FALSE KDE_NO_UNDEFINED KDE_USE_NMCHECK_TRUE KDE_USE_NMCHECK_FALSE LN_S ECHO RANLIB ac_ct_RANLIB EGREP LIBTOOL KDE_PLUGIN MSGFMT GMSGFMT XGETTEXT LIBUTIL LIBCOMPAT LIBCRYPT LIBRESOLV LIB_POLL FRAMEWORK_COREAUDIO LIBSOCKET X_EXTRA_LIBS LIBUCB LIBDL LIBXINERAMA X_PRE_LIBS LIB_X11 LIB_XRENDER LIBSM X_INCLUDES X_LDFLAGS x_includes x_libraries QTE_NORTTI LIB_XEXT LIBPTHREAD USE_THREADS KDE_MT_LDFLAGS KDE_MT_LIBS USER_INCLUDES USER_LDFLAGS LIBZ LIBPNG LIBJPEG qt_libraries qt_includes QT_INCLUDES QT_LDFLAGS PERL MOC UIC UIC_TR LIB_QT LIB_QPE kde_qtver KDE_EXTRA_RPATH KDE_RPATH X_RPATH kde_libraries kde_includes KDE_LDFLAGS KDE_INCLUDES all_includes all_libraries AUTODIRS include_ARTS_TRUE include_ARTS_FALSE DCOPIDL DCOPIDL2CPP DCOP_DEPENDENCIES MCOPIDL ARTSCCONFIG KDECONFIG MEINPROC KDE_XSL_STYLESHEET kde_libs_prefix kde_libs_htmldir kde_htmldir kde_appsdir kde_icondir kde_sounddir kde_datadir kde_locale kde_confdir kde_mimedir kde_wallpaperdir kde_bindir kde_templatesdir kde_servicesdir kde_servicetypesdir kde_moduledir kdeinitdir kde_styledir kde_widgetdir LIB_KDECORE LIB_KDEUI LIB_KIO LIB_SMB LIB_KAB LIB_KABC LIB_KHTML LIB_KSPELL LIB_KPARTS LIB_KDEPRINT LIB_KUTILS LIB_KDEPIM LIB_KSYCOCA LIB_KFILE LIB_KFM LIBXSLT_LIBS LIBXSLT_CFLAGS LIBXSLT_RPATH LIBXML_LIBS LIBXML_CFLAGS LIBXML_RPATH ALLOCA TOPSUBDIRS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CONF_FILES CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE WOVERLOADED_VIRTUAL USE_EXCEPTIONS USE_RTTI CXXCPP NOOPT_CXXFLAGS NOOPT_CFLAGS KDE_USE_FINAL_TRUE KDE_USE_FINAL_FALSE KDE_USE_CLOSURE_TRUE KDE_USE_CLOSURE_FALSE KDE_NO_UNDEFINED KDE_USE_NMCHECK_TRUE KDE_USE_NMCHECK_FALSE LN_S ECHO RANLIB ac_ct_RANLIB EGREP LIBTOOL KDE_PLUGIN MSGFMT GMSGFMT XGETTEXT LIBUTIL LIBCOMPAT LIBCRYPT LIBRESOLV LIB_POLL FRAMEWORK_COREAUDIO LIBSOCKET X_EXTRA_LIBS LIBUCB LIBDL LIBXINERAMA X_PRE_LIBS LIB_X11 LIB_XRENDER LIBSM X_INCLUDES X_LDFLAGS x_includes x_libraries QTE_NORTTI LIB_XEXT LIBPTHREAD USE_THREADS KDE_MT_LDFLAGS KDE_MT_LIBS USER_INCLUDES USER_LDFLAGS LIBZ LIBPNG LIBJPEG qt_libraries qt_includes QT_INCLUDES QT_LDFLAGS PERL MOC UIC UIC_TR LIB_QT LIB_QPE kde_qtver KDE_EXTRA_RPATH KDE_RPATH X_RPATH kde_libraries kde_includes KDE_LDFLAGS KDE_INCLUDES all_includes all_libraries AUTODIRS include_ARTS_TRUE include_ARTS_FALSE DCOPIDL DCOPIDL2CPP DCOP_DEPENDENCIES MCOPIDL ARTSCCONFIG KDECONFIG MEINPROC KDE_XSL_STYLESHEET kde_libs_prefix kde_libs_htmldir kde_htmldir kde_appsdir kde_icondir kde_sounddir kde_datadir kde_locale kde_confdir kde_mimedir kde_wallpaperdir kde_bindir kde_templatesdir kde_servicesdir kde_servicetypesdir kde_moduledir kdeinitdir kde_styledir kde_widgetdir LIB_KDECORE LIB_KDEUI LIB_KIO LIB_SMB LIB_KAB LIB_KABC LIB_KHTML LIB_KSPELL LIB_KPARTS LIB_KDEPRINT LIB_KUTILS LIB_KDEPIM LIB_KSYCOCA LIB_KFILE LIB_KFM LIBXML_LIBS LIBXML_CFLAGS LIBXML_RPATH XMLCATALOG XML_CATALOG_FILE LIBXSLT_LIBS LIBXSLT_CFLAGS LIBXSLT_RPATH ALLOCA TOPSUBDIRS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1055,6 +1055,8 @@ Optional Packages:
   --with-qt-includes=DIR  where the Qt includes are.
   --with-qt-libraries=DIR where the Qt library is installed.
   --without-arts          build without aRts default=yes
+  --with-xml-catalog=CATALOG
+                          path to XML catalog, default=without-xml-catalog
 
 Some influential environment variables:
   CC          C compiler command
@@ -1857,7 +1859,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=bookcase
- VERSION=0.8
+ VERSION=0.8.1
 
 
 cat >>confdefs.h <<_ACEOF
@@ -6404,7 +6406,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6407 "configure"' > conftest.$ac_ext
+  echo '#line 6409 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9780,7 +9782,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9783 "configure"
+#line 9785 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9878,7 +9880,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9881 "configure"
+#line 9883 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12991,7 +12993,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12994 "configure"
+#line 12996 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13089,7 +13091,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13092 "configure"
+#line 13094 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15723,7 +15725,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 15726 "configure"
+#line 15728 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15821,7 +15823,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 15824 "configure"
+#line 15826 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23063,7 +23065,7 @@ for i in $jpeg_incdirs;
 do
   for j in jpeglib.h;
   do
-    echo "configure: 23066: $i/$j" >&5
+    echo "configure: 23068: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       jpeg_incdir=$i
@@ -23368,7 +23370,7 @@ for i in $qt_incdirs;
 do
   for j in $kde_qt_header;
   do
-    echo "configure: 23371: $i/$j" >&5
+    echo "configure: 23373: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       qt_incdir=$i
@@ -24181,7 +24183,7 @@ for i in $kde_incdirs;
 do
   for j in $kde_check_header;
   do
-    echo "configure: 24184: $i/$j" >&5
+    echo "configure: 24186: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_incdir=$i
@@ -24211,7 +24213,7 @@ for i in $kde_libdirs;
 do
   for j in $kde_check_lib;
   do
-    echo "configure: 24214: $i/$j" >&5
+    echo "configure: 24216: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_libdir=$i
@@ -24229,7 +24231,7 @@ for i in $kde_libdirs;
 do
   for j in "kde3/plugins/designer/kdewidgets.la";
   do
-    echo "configure: 24232: $i/$j" >&5
+    echo "configure: 24234: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_widgetdir=$i
@@ -25418,7 +25420,7 @@ for i in $kde_sharedirs;
 do
   for j in apps/ksgmltools2/customization/kde-chunk.xsl;
   do
-    echo "configure: 25421: $i/$j" >&5
+    echo "configure: 25423: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       KDE_XSL_STYLESHEET=$i
@@ -25659,6 +25661,104 @@ fi
 
 
 
+
+
+
+# Check whether --with-xml-catalog or --without-xml-catalog was given.
+if test "${with_xml_catalog+set}" = set; then
+  withval="$with_xml_catalog"
+
+else
+  with_xml_catalog=no
+fi;
+
+if test x"$with_xml_catalog" != xno; then
+
+   echo "$as_me:$LINENO: checking for xmlcatalog" >&5
+echo $ECHO_N "checking for xmlcatalog... $ECHO_C" >&6
+   if test -n "$XMLCATALOG"; then
+        kde_cv_path="$XMLCATALOG";
+   else
+        kde_cache=`echo xmlcatalog | sed 'y%./+-%__p_%'`
+
+        if eval "test \"\${kde_cv_path_$kde_cache+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+        kde_cv_path="NONE"
+	dirs="${prefix}/bin ${exec_prefix}/bin /usr/bin /usr/local/bin /opt/local/bin"
+	kde_save_IFS=$IFS
+	IFS=':'
+	for dir in $PATH; do
+	  dirs="$dirs $dir"
+        done
+	IFS=$kde_save_IFS
+
+        for dir in $dirs; do
+	  if test -x "$dir/xmlcatalog"; then
+	    if test -n ""
+	    then
+              evalstr="$dir/xmlcatalog  2>&1 "
+	      if eval $evalstr; then
+                kde_cv_path="$dir/xmlcatalog"
+                break
+	      fi
+            else
+		kde_cv_path="$dir/xmlcatalog"
+                break
+	    fi
+          fi
+        done
+
+        eval "kde_cv_path_$kde_cache=$kde_cv_path"
+
+
+fi
+
+
+      eval "kde_cv_path=\"`echo '$kde_cv_path_'$kde_cache`\""
+
+   fi
+
+   if test -z "$kde_cv_path" || test "$kde_cv_path" = NONE; then
+      echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+
+    { { echo "$as_me:$LINENO: error: Could not find xmlcatalog anywhere, check ftp://xmlsoft.org/ for libxml2 >= 2.4.23. If you are using pre-packaged libraries, be sure to have the utility files installed as well, which may be called libxml2-utils or something similar." >&5
+echo "$as_me: error: Could not find xmlcatalog anywhere, check ftp://xmlsoft.org/ for libxml2 >= 2.4.23. If you are using pre-packaged libraries, be sure to have the utility files installed as well, which may be called libxml2-utils or something similar." >&2;}
+   { (exit 1); exit 1; }; }
+
+   else
+      echo "$as_me:$LINENO: result: $kde_cv_path" >&5
+echo "${ECHO_T}$kde_cv_path" >&6
+      XMLCATALOG=$kde_cv_path
+
+   fi
+
+
+
+
+  if test x"$with_xml_catalog" = xyes; then
+    XML_CATALOG_FILE="/etc/xml/catalog"
+  else
+    XML_CATALOG_FILE="$with_xml_catalog"
+  fi
+
+  echo "$as_me:$LINENO: checking for XML catalog" >&5
+echo $ECHO_N "checking for XML catalog... $ECHO_C" >&6
+  if test -f "$XML_CATALOG_FILE"; then
+    echo "$as_me:$LINENO: result: $XML_CATALOG_FILE" >&5
+echo "${ECHO_T}$XML_CATALOG_FILE" >&6
+  else
+    { { echo "$as_me:$LINENO: error: $XML_CATALOG_FILE not found" >&5
+echo "$as_me: error: $XML_CATALOG_FILE not found" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+fi
+
+
    echo "$as_me:$LINENO: checking for xslt-config" >&5
 echo $ECHO_N "checking for xslt-config... $ECHO_C" >&6
    if test -n "$XSLT_CONFIG"; then
@@ -25741,11 +25841,6 @@ echo "$as_me: error: You need at least libxslt 1.0.19." >&2;}
    { (exit 1); exit 1; }; }
   fi
 fi
-
-
-
-
-
 
 
 
@@ -29188,12 +29283,14 @@ s,@LIB_KDEPIM@,$LIB_KDEPIM,;t t
 s,@LIB_KSYCOCA@,$LIB_KSYCOCA,;t t
 s,@LIB_KFILE@,$LIB_KFILE,;t t
 s,@LIB_KFM@,$LIB_KFM,;t t
-s,@LIBXSLT_LIBS@,$LIBXSLT_LIBS,;t t
-s,@LIBXSLT_CFLAGS@,$LIBXSLT_CFLAGS,;t t
-s,@LIBXSLT_RPATH@,$LIBXSLT_RPATH,;t t
 s,@LIBXML_LIBS@,$LIBXML_LIBS,;t t
 s,@LIBXML_CFLAGS@,$LIBXML_CFLAGS,;t t
 s,@LIBXML_RPATH@,$LIBXML_RPATH,;t t
+s,@XMLCATALOG@,$XMLCATALOG,;t t
+s,@XML_CATALOG_FILE@,$XML_CATALOG_FILE,;t t
+s,@LIBXSLT_LIBS@,$LIBXSLT_LIBS,;t t
+s,@LIBXSLT_CFLAGS@,$LIBXSLT_CFLAGS,;t t
+s,@LIBXSLT_RPATH@,$LIBXSLT_RPATH,;t t
 s,@ALLOCA@,$ALLOCA,;t t
 s,@TOPSUBDIRS@,$TOPSUBDIRS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
